// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/keyval/keyval.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Mensajes principales --- //
type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Máximo 128 bytes (validado en servidor)
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Sin límite de tamaño
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// --- Operación Set --- //
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *KeyValuePair          `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetPair() *KeyValuePair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Ej: "key.abc (128B) set with value (512B)"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{2}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Operación Get --- //
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // <-- CAMBIO CRÍTICO AQUÍ (de string a bytes)
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// --- Operación GetPrefix (Streaming) --- //
type GetPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // Prefijo a buscar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixRequest) Reset() {
	*x = GetPrefixRequest{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixRequest) ProtoMessage() {}

func (x *GetPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixRequest.ProtoReflect.Descriptor instead.
func (*GetPrefixRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{5}
}

func (x *GetPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type GetPrefixStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetPrefixStreamResponse_Pair
	//	*GetPrefixStreamResponse_TotalMatches
	Response      isGetPrefixStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixStreamResponse) Reset() {
	*x = GetPrefixStreamResponse{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixStreamResponse) ProtoMessage() {}

func (x *GetPrefixStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixStreamResponse.ProtoReflect.Descriptor instead.
func (*GetPrefixStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{6}
}

func (x *GetPrefixStreamResponse) GetResponse() isGetPrefixStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetPrefixStreamResponse) GetPair() *KeyValuePair {
	if x != nil {
		if x, ok := x.Response.(*GetPrefixStreamResponse_Pair); ok {
			return x.Pair
		}
	}
	return nil
}

func (x *GetPrefixStreamResponse) GetTotalMatches() uint32 {
	if x != nil {
		if x, ok := x.Response.(*GetPrefixStreamResponse_TotalMatches); ok {
			return x.TotalMatches
		}
	}
	return 0
}

type isGetPrefixStreamResponse_Response interface {
	isGetPrefixStreamResponse_Response()
}

type GetPrefixStreamResponse_Pair struct {
	Pair *KeyValuePair `protobuf:"bytes,1,opt,name=pair,proto3,oneof"` // Pares enviados uno a uno
}

type GetPrefixStreamResponse_TotalMatches struct {
	TotalMatches uint32 `protobuf:"varint,2,opt,name=total_matches,json=totalMatches,proto3,oneof"` // Opcional: Total de coincidencias (último mensaje)
}

func (*GetPrefixStreamResponse_Pair) isGetPrefixStreamResponse_Response() {}

func (*GetPrefixStreamResponse_TotalMatches) isGetPrefixStreamResponse_Response() {}

// --- Estadísticas (oculto) --- //
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{7}
}

type StatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalKeys        uint64                 `protobuf:"varint,1,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	TotalSizeBytes   uint64                 `protobuf:"varint,2,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	SetOperations    uint64                 `protobuf:"varint,3,opt,name=set_operations,json=setOperations,proto3" json:"set_operations,omitempty"`
	GetOperations    uint64                 `protobuf:"varint,4,opt,name=get_operations,json=getOperations,proto3" json:"get_operations,omitempty"`
	PrefixOperations uint64                 `protobuf:"varint,5,opt,name=prefix_operations,json=prefixOperations,proto3" json:"prefix_operations,omitempty"`
	ActiveClients    uint64                 `protobuf:"varint,6,opt,name=active_clients,json=activeClients,proto3" json:"active_clients,omitempty"`
	OpsPerSecond     uint64                 `protobuf:"varint,7,opt,name=ops_per_second,json=opsPerSecond,proto3" json:"ops_per_second,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_proto_keyval_keyval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_keyval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_keyval_proto_rawDescGZIP(), []int{8}
}

func (x *StatResponse) GetTotalKeys() uint64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *StatResponse) GetTotalSizeBytes() uint64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *StatResponse) GetSetOperations() uint64 {
	if x != nil {
		return x.SetOperations
	}
	return 0
}

func (x *StatResponse) GetGetOperations() uint64 {
	if x != nil {
		return x.GetOperations
	}
	return 0
}

func (x *StatResponse) GetPrefixOperations() uint64 {
	if x != nil {
		return x.PrefixOperations
	}
	return 0
}

func (x *StatResponse) GetActiveClients() uint64 {
	if x != nil {
		return x.ActiveClients
	}
	return 0
}

func (x *StatResponse) GetOpsPerSecond() uint64 {
	if x != nil {
		return x.OpsPerSecond
	}
	return 0
}

var File_proto_keyval_keyval_proto protoreflect.FileDescriptor

const file_proto_keyval_keyval_proto_rawDesc = "" +
	"\n" +
	"\x19proto/keyval/keyval.proto\x12\akvstore\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"7\n" +
	"\n" +
	"SetRequest\x12)\n" +
	"\x04pair\x18\x01 \x01(\v2\x15.kvstore.KeyValuePairR\x04pair\"A\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"*\n" +
	"\x10GetPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"y\n" +
	"\x17GetPrefixStreamResponse\x12+\n" +
	"\x04pair\x18\x01 \x01(\v2\x15.kvstore.KeyValuePairH\x00R\x04pair\x12%\n" +
	"\rtotal_matches\x18\x02 \x01(\rH\x00R\ftotalMatchesB\n" +
	"\n" +
	"\bresponse\"\r\n" +
	"\vStatRequest\"\x9f\x02\n" +
	"\fStatResponse\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x01 \x01(\x04R\ttotalKeys\x12(\n" +
	"\x10total_size_bytes\x18\x02 \x01(\x04R\x0etotalSizeBytes\x12%\n" +
	"\x0eset_operations\x18\x03 \x01(\x04R\rsetOperations\x12%\n" +
	"\x0eget_operations\x18\x04 \x01(\x04R\rgetOperations\x12+\n" +
	"\x11prefix_operations\x18\x05 \x01(\x04R\x10prefixOperations\x12%\n" +
	"\x0eactive_clients\x18\x06 \x01(\x04R\ractiveClients\x12$\n" +
	"\x0eops_per_second\x18\a \x01(\x04R\fopsPerSecond2\xfc\x01\n" +
	"\x0fKeyValueService\x120\n" +
	"\x03Set\x12\x13.kvstore.SetRequest\x1a\x14.kvstore.SetResponse\x120\n" +
	"\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12P\n" +
	"\x0fGetPrefixStream\x12\x19.kvstore.GetPrefixRequest\x1a .kvstore.GetPrefixStreamResponse0\x01\x123\n" +
	"\x04Stat\x12\x14.kvstore.StatRequest\x1a\x15.kvstore.StatResponseB\x0fZ\rkvstore/protob\x06proto3"

var (
	file_proto_keyval_keyval_proto_rawDescOnce sync.Once
	file_proto_keyval_keyval_proto_rawDescData []byte
)

func file_proto_keyval_keyval_proto_rawDescGZIP() []byte {
	file_proto_keyval_keyval_proto_rawDescOnce.Do(func() {
		file_proto_keyval_keyval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keyval_keyval_proto_rawDesc), len(file_proto_keyval_keyval_proto_rawDesc)))
	})
	return file_proto_keyval_keyval_proto_rawDescData
}

var file_proto_keyval_keyval_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_keyval_keyval_proto_goTypes = []any{
	(*KeyValuePair)(nil),            // 0: kvstore.KeyValuePair
	(*SetRequest)(nil),              // 1: kvstore.SetRequest
	(*SetResponse)(nil),             // 2: kvstore.SetResponse
	(*GetRequest)(nil),              // 3: kvstore.GetRequest
	(*GetResponse)(nil),             // 4: kvstore.GetResponse
	(*GetPrefixRequest)(nil),        // 5: kvstore.GetPrefixRequest
	(*GetPrefixStreamResponse)(nil), // 6: kvstore.GetPrefixStreamResponse
	(*StatRequest)(nil),             // 7: kvstore.StatRequest
	(*StatResponse)(nil),            // 8: kvstore.StatResponse
}
var file_proto_keyval_keyval_proto_depIdxs = []int32{
	0, // 0: kvstore.SetRequest.pair:type_name -> kvstore.KeyValuePair
	0, // 1: kvstore.GetPrefixStreamResponse.pair:type_name -> kvstore.KeyValuePair
	1, // 2: kvstore.KeyValueService.Set:input_type -> kvstore.SetRequest
	3, // 3: kvstore.KeyValueService.Get:input_type -> kvstore.GetRequest
	5, // 4: kvstore.KeyValueService.GetPrefixStream:input_type -> kvstore.GetPrefixRequest
	7, // 5: kvstore.KeyValueService.Stat:input_type -> kvstore.StatRequest
	2, // 6: kvstore.KeyValueService.Set:output_type -> kvstore.SetResponse
	4, // 7: kvstore.KeyValueService.Get:output_type -> kvstore.GetResponse
	6, // 8: kvstore.KeyValueService.GetPrefixStream:output_type -> kvstore.GetPrefixStreamResponse
	8, // 9: kvstore.KeyValueService.Stat:output_type -> kvstore.StatResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_keyval_keyval_proto_init() }
func file_proto_keyval_keyval_proto_init() {
	if File_proto_keyval_keyval_proto != nil {
		return
	}
	file_proto_keyval_keyval_proto_msgTypes[6].OneofWrappers = []any{
		(*GetPrefixStreamResponse_Pair)(nil),
		(*GetPrefixStreamResponse_TotalMatches)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keyval_keyval_proto_rawDesc), len(file_proto_keyval_keyval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keyval_keyval_proto_goTypes,
		DependencyIndexes: file_proto_keyval_keyval_proto_depIdxs,
		MessageInfos:      file_proto_keyval_keyval_proto_msgTypes,
	}.Build()
	File_proto_keyval_keyval_proto = out.File
	file_proto_keyval_keyval_proto_goTypes = nil
	file_proto_keyval_keyval_proto_depIdxs = nil
}
